version: '3'

services:
#  db:
#    image: mysql: 5.6.41
#    restart: always
#    ports:
#      - '3333:3306'
#    volumes:
  php-fpm:
    build:
      context: ./docker/php
    volumes:
      - ./src:/var/www/html

  nginx:
    build:
      context: ./docker/nginx
    volumes:
        - ./src:/var/www/html
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/nginx/sites/:/etc/nginx/sites-available
        - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "8000:80"
      - "443:443"

  database:
    build:
      context: ./docker/mysql
    ports:
      - '3333:3306'
    environment:
      - MYSQL_DATABASE=sadasweb_micnoi
      - MYSQL_USER=sadasweb_micnoi
      - MYSQL_PASSWORD=sadasweb_micnoi
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - ./docker/mysql/:/var/lib/mysql